export const metadata = {
  title: "Keen-Keeper | Stats",
  description: "Generated by create next app",
};

const StatsPage = () => {
    return (
        <div>
           this is Stats 
        </div>
    );
};

export default StatsPage;