export const metadata = {
  title: "Keen-Keeper | TimeLine",
  description: "Generated by create next app",
};

const TimelinePage = () => {
  return <div><h1>this is timeLine Page</h1></div>;
};

export default TimelinePage;
