export const metadata = {
  title: "Keen-Keeper | Home",
  description: "Generated by create next app",
};


import { FaPlus } from "react-icons/fa";

import FriendsStats from "@/components/friendsStats/FriendsStats";
import Friends from "./friends/page";
export default function Home() {
  
  return (
    <section className=" mb-12 px-4">
      {/* Hero Section */}
      <div className="flex flex-col items-center text-center space-y-6 mx-auto max-w-3xl mb-12">
        <h1 className="text-4xl md:text-5xl font-bold text-[#244D3F] leading-tight">
          Friends to keep close in your life
        </h1>
        <p className="text-[#64748B] text-lg">
          Your personal shelf of meaningful connections. Browse, tend, and
          nurture the relationships that matter most.
        </p>
        <button className="btn bg-[#244D3F] hover:bg-[#1a3a2f] border-none text-white px-8">
          <FaPlus className="mr-2" /> Add a Friend
        </button>
      </div>

      {/* FriendStats Grid */}
    <FriendsStats></FriendsStats>
      {/* friends Grid */}
      <Friends></Friends>

      
 
    </section>
  );
}
