export const metadata = {
  title: "Keen-Keeper | Home",
  description: "Generated by create next app",
};
import { FaPlus } from "react-icons/fa";

export default function Home() {
  return (
   <section className="mb-12 px-4">
  {/* Hero Section */}
  <div className="flex flex-col items-center text-center space-y-6 mx-auto max-w-3xl mb-12">
    <h1 className="text-4xl md:text-5xl font-bold text-[#244D3F] leading-tight">
      Friends to keep close in your life
    </h1>
    <p className="text-[#64748B] text-lg">
      Your personal shelf of meaningful connections. Browse, tend, and
      nurture the relationships that matter most.
    </p>
    <button className="btn bg-[#244D3F] hover:bg-[#1a3a2f] border-none text-white px-8">
      <FaPlus className="mr-2" /> Add a Friend
    </button>
  </div>

  {/* Stats Grid */}
  <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4 max-w-6xl mx-auto">
    <div className="flex flex-col items-center justify-center p-6 bg-white rounded-2xl shadow-sm border border-slate-100 transition-transform hover:scale-[1.02]">
      <span className="text-3xl font-bold text-slate-800">10</span>
      <span className="text-xs uppercase tracking-wider text-slate-400 font-semibold mt-1">
        Total Friends
      </span>
    </div>

    <div className="flex flex-col items-center justify-center p-6 bg-white rounded-2xl shadow-sm border border-slate-100 transition-transform hover:scale-[1.02]">
      <span className="text-3xl font-bold text-green-600">3</span>
      <span className="text-xs uppercase tracking-wider text-slate-400 font-semibold mt-1">
        On Track
      </span>
    </div>

    <div className="flex flex-col items-center justify-center p-6 bg-white rounded-2xl shadow-sm border border-slate-100 transition-transform hover:scale-[1.02]">
      <span className="text-3xl font-bold text-amber-500">6</span>
      <span className="text-xs uppercase tracking-wider text-slate-400 font-semibold mt-1">
        Need Attention
      </span>
    </div>

    <div className="flex flex-col items-center justify-center p-6 bg-white rounded-2xl shadow-sm border border-slate-100 transition-transform hover:scale-[1.02]">
      <span className="text-3xl font-bold text-blue-600">12</span>
      <span className="text-xs uppercase tracking-wider text-slate-400 font-semibold mt-1">
        Interactions
      </span>
    </div>
  </div>
  {/* friends Grid */}
</section>
  );
}
